/* Generated by the Nim Compiler v2.1.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI704643086 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI939524173 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI939524179 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555163 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555170 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555168 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555168 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555168.node = NNI33555168;
NTI33555170.base = NTI33555167;
NTI33555171.base = NTI33555167;
var NNI33555167 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555170, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555171, name: "up", sons: null}]};
NTI33555167.node = NNI33555167;
var NNI33555163 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555163.node = NNI33555163;
NTI33555167.base = NTI33555163;
NTI33555168.base = NTI33555167;
NTI134217741.base = NTI33555168;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555168;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555168;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555168;
var NNI939524179 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI939524173, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI939524179.node = NNI939524179;
var NNI704643086 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI704643086.node = NNI704643086;

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function toJSStr(s_p0) {
  var result_33556889 = null;

    var res_33556930 = newSeq__system_u2474((s_p0).length);
    var i_33556931 = 0;
    var j_33556932 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556931 < (s_p0).length)) break Label2;
          var c_33556933 = s_p0[i_33556931];
          if ((c_33556933 < 128)) {
          res_33556930[j_33556932] = String.fromCharCode(c_33556933);
          i_33556931 += 1;
          }
          else {
            var helper_33556945 = newSeq__system_u2474(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556946 = c_33556933.toString(16);
                  if ((((code_33556946) == null ? 0 : (code_33556946).length) == 1)) {
                  helper_33556945.push("%0");;
                  }
                  else {
                  helper_33556945.push("%");;
                  }
                  
                  helper_33556945.push(code_33556946);;
                  i_33556931 += 1;
                  if ((((s_p0).length <= i_33556931) || (s_p0[i_33556931] < 128))) {
                  break Label3;
                  }
                  
                  c_33556933 = s_p0[i_33556931];
                }
            };
++excHandler;
            try {
            res_33556930[j_33556932] = decodeURIComponent(helper_33556945.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556930[j_33556932] = helper_33556945.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556932 += 1;
        }
    };
    if (res_33556930.length < j_33556932) { for (var i = res_33556930.length ; i < j_33556932 ; ++i) res_33556930.push(null); }
               else { res_33556930.length = j_33556932; };
    result_33556889 = res_33556930.join("");

  return result_33556889;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557311 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557311 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557311;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557263 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2811(ti_p2))) {
      result_33557263 = src_p1;
      }
      else {
        result_33557263 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557263 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557263 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557263 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557263 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557263, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557263 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557263 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557263 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557263[i] = nimCopy(result_33557263[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557263 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557263 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557263[i] = nimCopy(result_33557263[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557263 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557263 = src_p1;
      break;
    }

  return result_33557263;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557306 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557306 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557306;

}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
var ConstSet2 = setConstr([65, 90]);
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);
var ConstSet9 = setConstr([65, 90], [97, 122]);

function nimMax(a_p0, b_p1) {
    var Temporary1;

  var result_33557094 = 0;

  BeforeRet: {
    if ((b_p1 <= a_p0)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557094 = Temporary1;
    break BeforeRet;
  };

  return result_33557094;

}

function nimMin(a_p0, b_p1) {
    var Temporary1;

  var result_33557090 = 0;

  BeforeRet: {
    if ((a_p0 <= b_p1)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557090 = Temporary1;
    break BeforeRet;
  };

  return result_33557090;

}

function addChar(x_p0, c_p1) {
    x_p0.push(c_p1);

  
}
var objectID_1157628079 = [0];

function setTheme(theme_p0) {
    document.documentElement.setAttribute("data-theme", theme_p0);
    window.localStorage.setItem("theme", theme_p0);

  
}

function add__system_u1931(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function newSeq__system_u2474(len_p0) {
  var result_33556909 = [];

    result_33556909 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556909[i] = null; }
  return result_33556909;

}

function unhandledException(e_p0) {
    var buf_33556637 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556637[0].push.apply(buf_33556637[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556637[0].push.apply(buf_33556637[0], e_p0.message);;
    }
    else {
    buf_33556637[0].push.apply(buf_33556637[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556637[0].push.apply(buf_33556637[0], [32,91]);;
    add__system_u1931(buf_33556637, 0, e_p0.name);
    buf_33556637[0].push.apply(buf_33556637[0], [93,10]);;
    var cbuf_33556638 = toJSStr(buf_33556637[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556638);
  }
  else {
    throw cbuf_33556638;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars__stdZprivateZdigitsutils_u199(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_301990093 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_301990093, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990107 = 0;
      var i_553649322 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_553649322 < n_p3)) break Label4;
            iHEX60gensym4_301990107 = i_553649322;
            result_p0[result_p0_Idx][chckIndx(addInt(old_301990093, iHEX60gensym4_301990107), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_301990107), 0, (x_p1).length - 1));
            i_553649322 = addInt(i_553649322, 1);
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u195(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u199(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u220(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u195(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u238(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u220(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u8(x_p0) {
  var result_385875978 = [[]];

    addInt__stdZprivateZdigitsutils_u238(result_385875978, 0, x_p0);

  return result_385875978[0];

}

function isFatPointer__system_u2811(ti_p0) {
  var result_33557245 = false;

  BeforeRet: {
    result_33557245 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557245;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24__systemZdollars_u8(i_p0) || [],[32,110,111,116,32,105,110,32] || [],HEX24__systemZdollars_u8(a_p1) || [],[32,46,46,32] || [],HEX24__systemZdollars_u8(b_p2) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function sysFatal__stdZassertions_u45(message_p1) {
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert__stdZassertions_u43(msg_p0) {
    sysFatal__stdZassertions_u45(msg_p0);

  
}

function failedAssertImpl__stdZassertions_u85(msg_p0) {
    raiseAssert__stdZassertions_u43(msg_p0);

  
}

function onDOMLoaded(e_p0) {
            
function HEX3Aanonymous__dochack_u64(event_p0) {
                event_p0.target.parentNode.style.display = "none";
                event_p0.target.parentNode.nextSibling.style.display = "inline";

              
            }

    document.getElementById("theme-select").value = window.localStorage.getItem("theme");
    Label1: {
      var pragmaDots_553648191 = null;
      var colontmp__553649313 = [];
      colontmp__553649313 = document.getElementsByClassName("pragmadots");
      var i_553649315 = 0;
      var L_553649316 = (colontmp__553649313).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649315 < L_553649316)) break Label3;
            pragmaDots_553648191 = colontmp__553649313[chckIndx(i_553649315, 0, (colontmp__553649313).length - 1)];
            pragmaDots_553648191.onclick = HEX3Aanonymous__dochack_u64;
            i_553649315 += 1;
            if (!(((colontmp__553649313).length == L_553649316))) {
            failedAssertImpl__stdZassertions_u85(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };

  
}

function isWhitespace__dochack_u405(x_p0) {
  var result_553648535 = false;

    result_553648535 = (((x_p0.nodeName == "#text") && !/\S/.test(x_p0.textContent)) || (x_p0.nodeName == "#comment"));

  return result_553648535;

}

function toToc__dochack_u408(x_p0, father_p1) {
                var Temporary5;
            var Temporary6;
            var Temporary7;
            var Temporary8;
      var Temporary15;

    if ((x_p0.nodeName == "UL")) {
    var f_553648546 = {heading: null, kids: [], sortId: (father_p1.kids).length, doSort: false};
    var i_553648547 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_553648547 < x_p0.childNodes.length)) break Label2;
          var nxt_553648548 = addInt(i_553648547, 1);
          Label3: {
              Label4: while (true) {
                if (!(nxt_553648548 < x_p0.childNodes.length)) Temporary5 = false; else {                  Temporary5 = isWhitespace__dochack_u405(x_p0.childNodes[nxt_553648548]);                }              if (!Temporary5) break Label4;
                nxt_553648548 = addInt(nxt_553648548, 1);
              }
          };
            if (!(nxt_553648548 < x_p0.childNodes.length)) Temporary8 = false; else {              Temporary8 = (x_p0.childNodes[i_553648547].nodeName == "LI");            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = (x_p0.childNodes[i_553648547].childNodes.length == 1);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = (x_p0.childNodes[nxt_553648548].nodeName == "UL");            }          if (Temporary6) {
          var e_553648560 = {heading: x_p0.childNodes[i_553648547].childNodes[0], kids: [], sortId: (f_553648546.kids).length, doSort: false};
          var it_553648561 = x_p0.childNodes[nxt_553648548];
          Label9: {
            var j_553648566 = 0;
            var colontmp__553649329 = 0;
            colontmp__553649329 = it_553648561.childNodes.length;
            var i_553649330 = 0;
            Label10: {
                Label11: while (true) {
                if (!(i_553649330 < colontmp__553649329)) break Label11;
                  j_553648566 = i_553649330;
                  toToc__dochack_u408(it_553648561.childNodes[j_553648566], e_553648560);
                  i_553649330 = addInt(i_553649330, 1);
                }
            };
          };
          f_553648546.kids.push(e_553648560);;
          i_553648547 = addInt(nxt_553648548, 1);
          }
          else {
            toToc__dochack_u408(x_p0.childNodes[i_553648547], f_553648546);
            i_553648547 = addInt(i_553648547, 1);
          }
          
        }
    };
    father_p1.kids.push(f_553648546);;
    }
    else {
    if (isWhitespace__dochack_u405(x_p0)) {
    }
    else {
    if ((x_p0.nodeName == "LI")) {
    var idx_553648583 = [];
    Label12: {
      var i_553648588 = 0;
      var colontmp__553649333 = 0;
      colontmp__553649333 = x_p0.childNodes.length;
      var i_553649334 = 0;
      Label13: {
          Label14: while (true) {
          if (!(i_553649334 < colontmp__553649333)) break Label14;
            i_553648588 = i_553649334;
            if (!(isWhitespace__dochack_u405(x_p0.childNodes[i_553648588]))) {
            idx_553648583.push(i_553648588);;
            }
            
            i_553649334 = addInt(i_553649334, 1);
          }
      };
    };
      if (!((idx_553648583).length == 2)) Temporary15 = false; else {        Temporary15 = (x_p0.childNodes[idx_553648583[chckIndx(1, 0, (idx_553648583).length - 1)]].nodeName == "UL");      }    if (Temporary15) {
    var e_553648604 = {heading: x_p0.childNodes[idx_553648583[chckIndx(0, 0, (idx_553648583).length - 1)]], kids: [], sortId: (father_p1.kids).length, doSort: false};
    var it_553648605 = x_p0.childNodes[idx_553648583[chckIndx(1, 0, (idx_553648583).length - 1)]];
    Label16: {
      var j_553648610 = 0;
      var colontmp__553649337 = 0;
      colontmp__553649337 = it_553648605.childNodes.length;
      var i_553649338 = 0;
      Label17: {
          Label18: while (true) {
          if (!(i_553649338 < colontmp__553649337)) break Label18;
            j_553648610 = i_553649338;
            toToc__dochack_u408(it_553648605.childNodes[j_553648610], e_553648604);
            i_553649338 = addInt(i_553649338, 1);
          }
      };
    };
    father_p1.kids.push(e_553648604);;
    }
    else {
      Label19: {
        var i_553648619 = 0;
        var colontmp__553649341 = 0;
        colontmp__553649341 = x_p0.childNodes.length;
        var i_553649342 = 0;
        Label20: {
            Label21: while (true) {
            if (!(i_553649342 < colontmp__553649341)) break Label21;
              i_553648619 = i_553649342;
              toToc__dochack_u408(x_p0.childNodes[i_553648619], father_p1);
              i_553649342 = addInt(i_553649342, 1);
            }
        };
      };
    }
    
    }
    else {
    father_p1.kids.push({heading: x_p0, kids: [], sortId: (father_p1.kids).length, doSort: false});;
    }
    }}

  
}

function extractItems__dochack_u197(x_p0, heading_p1, items_p2, items_p2_Idx) {
  BeforeRet: {
    if ((x_p0 == null)) {
    break BeforeRet;
    }
    
    if ((!((x_p0.heading == null)) && (x_p0.heading.textContent == heading_p1))) {
    Label1: {
      var i_553648345 = 0;
      var colontmp__553649345 = 0;
      colontmp__553649345 = (x_p0.kids).length;
      var i_553649346 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649346 < colontmp__553649345)) break Label3;
            i_553648345 = i_553649346;
            items_p2[items_p2_Idx].push(x_p0.kids[chckIndx(i_553648345, 0, (x_p0.kids).length - 1)].heading);;
            i_553649346 = addInt(i_553649346, 1);
          }
      };
    };
    }
    else {
      Label4: {
        var k_553648370 = null;
        var i_553649350 = 0;
        var L_553649351 = (x_p0.kids).length;
        Label5: {
            Label6: while (true) {
            if (!(i_553649350 < L_553649351)) break Label6;
              k_553648370 = x_p0.kids[chckIndx(i_553649350, 0, (x_p0.kids).length - 1)];
              extractItems__dochack_u197(k_553648370, heading_p1, items_p2, items_p2_Idx);
              i_553649350 += 1;
              if (!(((x_p0.kids).length == L_553649351))) {
              failedAssertImpl__stdZassertions_u85(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
              }
              
            }
        };
      };
    }
    
  };

  
}

function tree__dochack_u129(tag_p0, kids_p1) {
  var result_553648260 = null;

    result_553648260 = document.createElement(tag_p0);
    Label1: {
      var k_553648273 = null;
      var i_553649363 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649363 < (kids_p1).length)) break Label3;
            k_553648273 = kids_p1[chckIndx(i_553649363, 0, (kids_p1).length - 1)];
            result_553648260.appendChild(k_553648273);
            i_553649363 += 1;
          }
      };
    };

  return result_553648260;

}

function text__dochack_u153(s_p0) {
  var result_553648283 = null;

    result_553648283 = document.createTextNode(s_p0);

  return result_553648283;

}

function uncovered__dochack_u595(x_p0) {
    var Temporary1;

  var result_553648725 = null;

  BeforeRet: {
    if ((((x_p0.kids).length == 0) && !((x_p0.heading == null)))) {
    if (!(x_p0.heading.hasOwnProperty('__karaxMarker__'))) {
    Temporary1 = x_p0;
    }
    else {
    Temporary1 = null;
    }
    
    result_553648725 = Temporary1;
    break BeforeRet;
    }
    
    result_553648725 = {heading: x_p0.heading, kids: [], sortId: x_p0.sortId, doSort: x_p0.doSort};
    Label2: {
      var k_553648740 = null;
      var i_553649370 = 0;
      var L_553649371 = (x_p0.kids).length;
      Label3: {
          Label4: while (true) {
          if (!(i_553649370 < L_553649371)) break Label4;
            k_553648740 = x_p0.kids[chckIndx(i_553649370, 0, (x_p0.kids).length - 1)];
            var y_553648741 = uncovered__dochack_u595(k_553648740);
            if (!((y_553648741 == null))) {
            result_553648725.kids.push(y_553648741);;
            }
            
            i_553649370 += 1;
            if (!(((x_p0.kids).length == L_553649371))) {
            failedAssertImpl__stdZassertions_u85(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (((result_553648725.kids).length == 0)) {
    result_553648725 = null;
    }
    
  };

  return result_553648725;

}

function mergeTocs__dochack_u625(orig_p0, news_p1) {
  var result_553648756 = null;

    result_553648756 = uncovered__dochack_u595(orig_p0);
    if ((result_553648756 == null)) {
    result_553648756 = news_p1;
    }
    else {
      Label1: {
        var i_553648768 = 0;
        var colontmp__553649366 = 0;
        colontmp__553649366 = (news_p1.kids).length;
        var i_553649367 = 0;
        Label2: {
            Label3: while (true) {
            if (!(i_553649367 < colontmp__553649366)) break Label3;
              i_553648768 = i_553649367;
              result_553648756.kids.push(news_p1.kids[chckIndx(i_553648768, 0, (news_p1.kids).length - 1)]);;
              i_553649367 = addInt(i_553649367, 1);
            }
        };
      };
    }
    

  return result_553648756;

}

function buildToc__dochack_u645(orig_p0, types_p1, procs_p2) {
  var result_553648777 = null;

    var newStuff_553648782 = {heading: null, kids: [], doSort: true, sortId: 0};
    Label1: {
      var t_553648786 = null;
      var i_553649358 = 0;
      var L_553649359 = (types_p1).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649358 < L_553649359)) break Label3;
            t_553648786 = types_p1[chckIndx(i_553649358, 0, (types_p1).length - 1)];
            var c_553648791 = {heading: t_553648786.cloneNode(true), kids: [], doSort: true, sortId: 0};
            t_553648786.__karaxMarker__ = true;
            Label4: {
              var p_553648795 = null;
              var i_553649355 = 0;
              var L_553649356 = (procs_p2).length;
              Label5: {
                  Label6: while (true) {
                  if (!(i_553649355 < L_553649356)) break Label6;
                    p_553648795 = procs_p2[chckIndx(i_553649355, 0, (procs_p2).length - 1)];
                    if (!(p_553648795.hasOwnProperty('__karaxMarker__'))) {
                    var xx_553648796 = p_553648795.parentNode.getElementsByClassName("attachedType");
                    if ((((xx_553648796).length == 1) && (xx_553648796[chckIndx(0, 0, (xx_553648796).length - 1)].textContent == t_553648786.textContent))) {
                    var q_553648801 = tree__dochack_u129("A", [text__dochack_u153(p_553648795.title)]);
                    q_553648801.setAttribute("href", p_553648795.getAttribute("href"));
                    c_553648791.kids.push({heading: q_553648801, kids: [], sortId: 0, doSort: false});;
                    p_553648795.__karaxMarker__ = true;
                    }
                    
                    }
                    
                    i_553649355 += 1;
                    if (!(((procs_p2).length == L_553649356))) {
                    failedAssertImpl__stdZassertions_u85(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                    }
                    
                  }
              };
            };
            newStuff_553648782.kids.push(c_553648791);;
            i_553649358 += 1;
            if (!(((types_p1).length == L_553649359))) {
            failedAssertImpl__stdZassertions_u85(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_553648777 = mergeTocs__dochack_u625(orig_p0, newStuff_553648782);

  return result_553648777;

}

function add__dochack_u146(parent_p0, kid_p1) {
    if (((parent_p0.nodeName == "TR") && ((kid_p1.nodeName == "TD") || (kid_p1.nodeName == "TH")))) {
    var k_553648277 = document.createElement("TD");
    k_553648277.appendChild(kid_p1);
    parent_p0.appendChild(k_553648277);
    }
    else {
    parent_p0.appendChild(kid_p1);
    }
    

  
}

function setClass__dochack_u150(e_p0, value_p1) {
    e_p0.setAttribute("class", value_p1);

  
}

function toHtml__dochack_u275(x_p0, isRoot_p1) {
    
function HEX3Aanonymous__dochack_u295(a_p0, b_p1) {
      var result_553648426 = 0;

      BeforeRet: {
        if ((!((a_p0.heading == null)) && !((b_p1.heading == null)))) {
        var x_553648435 = a_p0.heading.textContent;
        var y_553648436 = b_p1.heading.textContent;
        if ((x_553648435 < y_553648436)) {
        result_553648426 = (-1);
        break BeforeRet;
        }
        
        if ((y_553648436 < x_553648435)) {
        result_553648426 = 1;
        break BeforeRet;
        }
        
        result_553648426 = 0;
        break BeforeRet;
        }
        else {
          result_553648426 = subInt(a_p0.sortId, b_p1.sortId);
          break BeforeRet;
        }
        
      };

      return result_553648426;

    }

  var result_553648406 = null;

  BeforeRet: {
    if ((x_p0 == null)) {
    result_553648406 = null;
    break BeforeRet;
    }
    
    if (((x_p0.kids).length == 0)) {
    if ((x_p0.heading == null)) {
    result_553648406 = null;
    break BeforeRet;
    }
    
    result_553648406 = x_p0.heading.cloneNode(true);
    break BeforeRet;
    }
    
    result_553648406 = tree__dochack_u129("DIV", []);
    if ((!((x_p0.heading == null)) && !(x_p0.heading.hasOwnProperty('__karaxMarker__')))) {
    add__dochack_u146(result_553648406, x_p0.heading.cloneNode(true));
    }
    
    var ul_553648422 = tree__dochack_u129("UL", []);
    if (isRoot_p1) {
    setClass__dochack_u150(ul_553648422, "simple simple-toc");
    }
    else {
    setClass__dochack_u150(ul_553648422, "simple");
    }
    
    if (x_p0.doSort) {
    x_p0.kids.sort(HEX3Aanonymous__dochack_u295);
    }
    
    Label1: {
      var k_553648448 = null;
      var i_553649374 = 0;
      var L_553649375 = (x_p0.kids).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649374 < L_553649375)) break Label3;
            k_553648448 = x_p0.kids[chckIndx(i_553649374, 0, (x_p0.kids).length - 1)];
            var y_553648449 = toHtml__dochack_u275(k_553648448, false);
            if (!((y_553648449 == null))) {
            add__dochack_u146(ul_553648422, tree__dochack_u129("LI", [y_553648449]));
            }
            
            i_553649374 += 1;
            if (!(((x_p0.kids).length == L_553649375))) {
            failedAssertImpl__stdZassertions_u85(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (!((ul_553648422.childNodes.length == 0))) {
    add__dochack_u146(result_553648406, ul_553648422);
    }
    
    if ((result_553648406.childNodes.length == 0)) {
    result_553648406 = null;
    }
    
  };

  return result_553648406;

}

function replaceById__dochack_u156(id_p0, newTree_p1) {
    var x_553648287 = document.getElementById(id_p0);
    x_553648287.parentNode.replaceChild(newTree_p1, x_553648287);
    newTree_p1.id = id_p0;

  
}

function togglevis__dochack_u703(d_p0) {
    if ((d_p0.style.display == "none")) {
    d_p0.style.display = "inline";
    }
    else {
      d_p0.style.display = "none";
    }
    

  
}

function groupBy(value_p0) {
    var toc_553648835 = document.getElementById("toc-list");
    if ((alternative_553648830[0] == null)) {
    var tt_553648843 = {heading: null, kids: [], sortId: 0, doSort: false};
    toToc__dochack_u408(toc_553648835, tt_553648843);
    tt_553648843 = tt_553648843.kids[chckIndx(0, 0, (tt_553648843.kids).length - 1)];
    var types_553648848 = [[]];
    var procs_553648853 = [[]];
    extractItems__dochack_u197(tt_553648843, "Types", types_553648848, 0);
    extractItems__dochack_u197(tt_553648843, "Procs", procs_553648853, 0);
    extractItems__dochack_u197(tt_553648843, "Converters", procs_553648853, 0);
    extractItems__dochack_u197(tt_553648843, "Methods", procs_553648853, 0);
    extractItems__dochack_u197(tt_553648843, "Templates", procs_553648853, 0);
    extractItems__dochack_u197(tt_553648843, "Macros", procs_553648853, 0);
    extractItems__dochack_u197(tt_553648843, "Iterators", procs_553648853, 0);
    var ntoc_553648854 = buildToc__dochack_u645(tt_553648843, types_553648848[0], procs_553648853[0]);
    var x_553648855 = toHtml__dochack_u275(ntoc_553648854, true);
    alternative_553648830[0] = tree__dochack_u129("DIV", [x_553648855]);
    }
    
    if ((value_p0 == "type")) {
    replaceById__dochack_u156("tocRoot", alternative_553648830[0]);
    }
    else {
    replaceById__dochack_u156("tocRoot", tree__dochack_u129("DIV", []));
    }
    
    togglevis__dochack_u703(document.getElementById("toc-list"));

  
}

function HEX5BHEX5D__pureZstrutils_u1259(s_p0, x_p1) {
  var result_721421552 = [];

    var a_721421554 = x_p1.a;
    var L_721421556 = addInt(subInt(subInt((s_p0).length, x_p1.b), a_721421554), 1);
    result_721421552 = nimCopy(null, mnewString(chckRange(L_721421556, 0, 2147483647)), NTI33554449);
    Label1: {
      var i_721421561 = 0;
      var i_553649384 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649384 < L_721421556)) break Label3;
            i_721421561 = i_553649384;
            result_721421552[chckIndx(i_721421561, 0, (result_721421552).length - 1)] = s_p0[chckIndx(addInt(i_721421561, a_721421554), 0, (s_p0).length - 1)];
            i_553649384 = addInt(i_553649384, 1);
          }
      };
    };

  return result_721421552;

}

function HEX2EHEX2E__stdZenumutils_u103(a_p0, b_p1) {
  var result_939524206 = ({a: 0, b: 0});

    result_939524206 = nimCopy(result_939524206, {a: a_p0, b: b_p1}, NTI939524179);

  return result_939524206;

}
async function loadIndex__dochack_u923() {
  var result_553649053 = null;

  BeforeRet: {
    var indexURL_553649059 = document.getElementById("indexLink").getAttribute("href");
    var rootURL_553649084 = HEX5BHEX5D__pureZstrutils_u1259(cstrToNimstr(indexURL_553649059), HEX2EHEX2E__stdZenumutils_u103(0, 14));
    var resp_553649096 = (await (await fetch(indexURL_553649059)).text());
    var indexElem_553649097 = document.createElement("div");
    indexElem_553649097.innerHTML = resp_553649096;
    Label1: {
      var href_553649118 = null;
      var colontmp__553649378 = [];
      colontmp__553649378 = indexElem_553649097.getElementsByClassName("reference");
      var i_553649380 = 0;
      var L_553649381 = (colontmp__553649378).length;
      Label2: {
          Label3: while (true) {
          if (!(i_553649380 < L_553649381)) break Label3;
            href_553649118 = colontmp__553649378[chckIndx(i_553649380, 0, (colontmp__553649378).length - 1)];
            href_553649118.setAttribute("href", toJSStr((rootURL_553649084 || []).concat(cstrToNimstr(href_553649118.getAttribute("href")) || [])));
            db_553648872[0].push(href_553649118);;
            contents_553648873[0].push(href_553649118.getAttribute("data-doc-search-tag"));;
            i_553649380 += 1;
            if (!(((colontmp__553649378).length == L_553649381))) {
            failedAssertImpl__stdZassertions_u85(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_553649053 = undefined;
    break BeforeRet;
  };

  return result_553649053;

}

function then__dochack_u1099(future_p0, onSuccess_p1, onReject_p2) {
  var result_553649233 = null;

  BeforeRet: {
    var ret_553649243 = null;
    ret_553649243 = future_p0.then(onSuccess_p1, onReject_p2)
    result_553649233 = ret_553649243;
    break BeforeRet;
  };

  return result_553649233;

}

function nsuToLowerAsciiChar(c_p0) {
  var result_721420374 = 0;

    if ((ConstSet2[c_p0] != undefined)) {
    result_721420374 = (c_p0 ^ 32);
    }
    else {
      result_721420374 = c_p0;
    }
    

  return result_721420374;

}

function fuzzyMatch__fuzzysearch_u16(pattern_p0, str_p1) {
              var Temporary4;
              var Temporary5;
                var Temporary6;
      var Temporary7;
        var Temporary8;

  var result_704643093 = {Field0: 0, Field1: false};

    var scoreState_704643094 = (-100);
    var headerMatched_704643095 = false;
    var unmatchedLeadingCharCount_704643096 = 0;
    var consecutiveMatchCount_704643097 = 0;
    var strIndex_704643098 = 0;
    var patIndex_704643099 = 0;
    var score_704643100 = 0;
    Label1: {
        Label2: while (true) {
        if (!((strIndex_704643098 < ((str_p1) == null ? 0 : (str_p1).length)) && (patIndex_704643099 < ((pattern_p0) == null ? 0 : (pattern_p0).length)))) break Label2;
          Label3: {
            var patternChar_704643103 = nsuToLowerAsciiChar(pattern_p0.charCodeAt(chckIndx(patIndex_704643099, 0, (pattern_p0).length - 1)));
            var strChar_704643104 = nsuToLowerAsciiChar(str_p1.charCodeAt(chckIndx(strIndex_704643098, 0, (str_p1).length - 1)));
            if ((ConstSet3[patternChar_704643103] != undefined)) {
            patIndex_704643099 = addInt(patIndex_704643099, 1);
            break Label3;
            }
            
            if ((ConstSet4[strChar_704643104] != undefined)) {
            strIndex_704643098 = addInt(strIndex_704643098, 1);
            break Label3;
            }
            
            if ((!(headerMatched_704643095) && (strChar_704643104 == 58))) {
            headerMatched_704643095 = true;
            scoreState_704643094 = (-100);
            score_704643100 = ((Math.floor((0.5 * score_704643100))) | 0);
            patIndex_704643099 = 0;
            strIndex_704643098 = addInt(strIndex_704643098, 1);
            break Label3;
            }
            
            if ((strChar_704643104 == patternChar_704643103)) {
            switch (scoreState_704643094) {
            case (-100):
            case 20:
              scoreState_704643094 = 10;
              break;
            case 0:
              scoreState_704643094 = 5;
              score_704643100 = addInt(score_704643100, scoreState_704643094);
              break;
            case 10:
            case 5:
              consecutiveMatchCount_704643097 = addInt(consecutiveMatchCount_704643097, 1);
              scoreState_704643094 = 5;
              score_704643100 = addInt(score_704643100, mulInt(5, consecutiveMatchCount_704643097));
              if ((scoreState_704643094 == 10)) {
              score_704643100 = addInt(score_704643100, 10);
              }
              
              var onBoundary_704643156 = (patIndex_704643099 == ((pattern_p0) == null ? -1 : (pattern_p0).length - 1));
              if ((!(onBoundary_704643156) && (strIndex_704643098 < ((str_p1) == null ? -1 : (str_p1).length - 1)))) {
              var nextPatternChar_704643157 = nsuToLowerAsciiChar(pattern_p0.charCodeAt(chckIndx(addInt(patIndex_704643099, 1), 0, (pattern_p0).length - 1)));
              var nextStrChar_704643158 = nsuToLowerAsciiChar(str_p1.charCodeAt(chckIndx(addInt(strIndex_704643098, 1), 0, (str_p1).length - 1)));
              if (!!((ConstSet5[nextStrChar_704643158] != undefined))) Temporary4 = false; else {                Temporary4 = !((nextStrChar_704643158 == nextPatternChar_704643157));              }              onBoundary_704643156 = Temporary4;
              }
              
              if (onBoundary_704643156) {
              scoreState_704643094 = 20;
              score_704643100 = addInt(score_704643100, scoreState_704643094);
              }
              
              break;
            case (-1):
            case (-3):
              if (!((ConstSet6[str_p1.charCodeAt(chckIndx(subInt(strIndex_704643098, 1), 0, (str_p1).length - 1))] != undefined))) Temporary5 = true; else {                if (!(ConstSet7[str_p1.charCodeAt(chckIndx(subInt(strIndex_704643098, 1), 0, (str_p1).length - 1))] != undefined)) Temporary6 = false; else {                  Temporary6 = (ConstSet8[str_p1.charCodeAt(chckIndx(strIndex_704643098, 0, (str_p1).length - 1))] != undefined);                }                Temporary5 = Temporary6;              }              var isLeadingChar_704643182 = Temporary5;
              if (isLeadingChar_704643182) {
              scoreState_704643094 = 10;
              }
              else {
                scoreState_704643094 = 0;
                score_704643100 = addInt(score_704643100, scoreState_704643094);
              }
              
              break;
            }
            patIndex_704643099 = addInt(patIndex_704643099, 1);
            }
            else {
              switch (scoreState_704643094) {
              case (-100):
                scoreState_704643094 = (-3);
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                break;
              case 5:
                scoreState_704643094 = (-1);
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                consecutiveMatchCount_704643097 = 0;
                break;
              case (-3):
                if ((unmatchedLeadingCharCount_704643096 < 3)) {
                scoreState_704643094 = (-3);
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                }
                
                unmatchedLeadingCharCount_704643096 = addInt(unmatchedLeadingCharCount_704643096, 1);
                break;
              default: 
                scoreState_704643094 = (-1);
                score_704643100 = addInt(score_704643100, scoreState_704643094);
                break;
              }
            }
            
            strIndex_704643098 = addInt(strIndex_704643098, 1);
          };
        }
    };
      if (!(patIndex_704643099 == ((pattern_p0) == null ? 0 : (pattern_p0).length))) Temporary7 = false; else {        if ((strIndex_704643098 == ((str_p1) == null ? 0 : (str_p1).length))) Temporary8 = true; else {          Temporary8 = !((ConstSet9[str_p1.charCodeAt(chckIndx(strIndex_704643098, 0, (str_p1).length - 1))] != undefined));        }        Temporary7 = Temporary8;      }    if (Temporary7) {
    score_704643100 = addInt(score_704643100, 10);
    }
    
    var colontmp__553649397 = nimMax(0, score_704643100);
    var colontmp__553649398 = (0 < score_704643100);
    result_704643093 = nimCopy(result_704643093, {Field0: colontmp__553649397, Field1: colontmp__553649398}, NTI704643086);

  return result_704643093;

}

function escapeCString__dochack_u746(x_p0, x_p0_Idx) {
    var s_553648876 = [];
    Label1: {
      var c_553648877 = 0;
      var iHEX60gensym13_553649401 = 0;
      var nHEX60gensym13_553649402 = ((x_p0[x_p0_Idx]) == null ? 0 : (x_p0[x_p0_Idx]).length);
      Label2: {
          Label3: while (true) {
          if (!(iHEX60gensym13_553649401 < nHEX60gensym13_553649402)) break Label3;
            c_553648877 = x_p0[x_p0_Idx].charCodeAt(chckIndx(iHEX60gensym13_553649401, 0, (x_p0[x_p0_Idx]).length - 1));
            switch (c_553648877) {
            case 60:
              s_553648876.push.apply(s_553648876, [38,108,116,59]);;
              break;
            case 62:
              s_553648876.push.apply(s_553648876, [38,103,116,59]);;
              break;
            default: 
              addChar(s_553648876, c_553648877);;
              break;
            }
            iHEX60gensym13_553649401 += 1;
          }
      };
    };
    x_p0[x_p0_Idx] = toJSStr(s_553648876);

  
}

function dosearch__dochack_u750(value_p0) {
    
function HEX3Aanonymous__dochack_u778(a_p0, b_p1) {
      var result_553648919 = 0;

        result_553648919 = subInt(b_p1["Field1"], a_p0["Field1"]);

      return result_553648919;

    }

  var result_553648880 = null;

  BeforeRet: {
    if (((db_553648872[0]).length == 0)) {
    break BeforeRet;
    }
    
    var ul_553648884 = tree__dochack_u129("UL", []);
    result_553648880 = tree__dochack_u129("DIV", []);
    setClass__dochack_u150(result_553648880, "search_results");
    var matches_553648889 = [];
    Label1: {
      var i_553648897 = 0;
      var colontmp__553649388 = 0;
      colontmp__553649388 = (db_553648872[0]).length;
      var i_553649389 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_553649389 < colontmp__553649388)) break Label3;
            i_553648897 = i_553649389;
            Label4: {
              var c_553648898 = contents_553648873[0][chckIndx(i_553648897, 0, (contents_553648873[0]).length - 1)];
              if (((c_553648898 == "Examples") || (c_553648898 == "PEG construction"))) {
              break Label4;
              }
              
              var tmpTuple_553648899 = fuzzyMatch__fuzzysearch_u16(value_p0, c_553648898);
              var score_553648900 = tmpTuple_553648899["Field0"];
              var matched_553648901 = tmpTuple_553648899["Field1"];
              if (matched_553648901) {
              matches_553648889.push({Field0: db_553648872[0][chckIndx(i_553648897, 0, (db_553648872[0]).length - 1)], Field1: score_553648900});;
              }
              
            };
            i_553649389 = addInt(i_553649389, 1);
          }
      };
    };
    matches_553648889.sort(HEX3Aanonymous__dochack_u778);
    Label5: {
      var i_553648936 = 0;
      var colontmp__553649392 = 0;
      colontmp__553649392 = nimMin((matches_553648889).length, 29);
      var i_553649393 = 0;
      Label6: {
          Label7: while (true) {
          if (!(i_553649393 < colontmp__553649392)) break Label7;
            i_553648936 = i_553649393;
            matches_553648889[chckIndx(i_553648936, 0, (matches_553648889).length - 1)]["Field0"].innerHTML = matches_553648889[chckIndx(i_553648936, 0, (matches_553648889).length - 1)]["Field0"].getAttribute("data-doc-search-tag");
            escapeCString__dochack_u746(matches_553648889[chckIndx(i_553648936, 0, (matches_553648889).length - 1)]["Field0"], "innerHTML");
            add__dochack_u146(ul_553648884, tree__dochack_u129("LI", [matches_553648889[chckIndx(i_553648936, 0, (matches_553648889).length - 1)]["Field0"]]));
            i_553649393 = addInt(i_553649393, 1);
          }
      };
    };
    if ((ul_553648884.childNodes.length == 0)) {
    add__dochack_u146(result_553648880, tree__dochack_u129("B", [text__dochack_u153("no search results")]));
    }
    else {
      add__dochack_u146(result_553648880, tree__dochack_u129("B", [text__dochack_u153("search results")]));
      add__dochack_u146(result_553648880, ul_553648884);
    }
    
  };

  return result_553648880;

}

function search() {
    
function wrapper__dochack_u1084() {
        var elem_553649213 = document.getElementById("searchInput");
        var value_553649214 = elem_553649213.value;
        if (!((((value_553649214) == null ? 0 : (value_553649214).length) == 0))) {
        if ((oldtoc_553649207[0] == null)) {
        oldtoc_553649207[0] = document.getElementById("tocRoot");
        }
        
        var results_553649218 = dosearch__dochack_u750(value_553649214);
        replaceById__dochack_u156("tocRoot", results_553649218);
        }
        else {
        if (!((oldtoc_553649207[0] == null))) {
        replaceById__dochack_u156("tocRoot", oldtoc_553649207[0]);
        }
        }

      
    }

    if ((loadIndexFut_553649210[0] == null)) {
    loadIndexFut_553649210[0] = loadIndex__dochack_u923();
    var _ = then__dochack_u1099(loadIndexFut_553649210[0], wrapper__dochack_u1084, null);
    }
    
    if (!((timer_553649208[0] == null))) {
    clearTimeout(timer_553649208[0]);
    }
    
    timer_553649208[0] = setTimeout(wrapper__dochack_u1084, 400);

  
}

function copyToClipboard() {
    
    function updatePreTags() {

      const allPreTags = document.querySelectorAll("pre")
    
      allPreTags.forEach((e) => {
      
          const div = document.createElement("div")
          div.classList.add("copyToClipBoard")
    
          const preTag = document.createElement("pre")
          preTag.innerHTML = e.innerHTML
    
          const button = document.createElement("button")
          button.value = e.textContent.replace('...', '') 
          button.classList.add("copyToClipBoardBtn")
          button.style.cursor = "pointer"
    
          div.appendChild(preTag)
          div.appendChild(button)
    
          e.outerHTML = div.outerHTML
      
      })
    }


    function copyTextToClipboard(e) {
        const clipBoardContent = e.target.value
        navigator.clipboard.writeText(clipBoardContent).then(function() {
            e.target.style.setProperty("--clipboard-image", "var(--clipboard-image-selected)")
        }, function(err) {
            console.error("Could not copy text: ", err);
        });
    }

    window.addEventListener("click", (e) => {
        if (e.target.classList.contains("copyToClipBoardBtn")) {
            copyTextToClipboard(e)
          }
    })

    window.addEventListener("mouseover", (e) => {
        if (e.target.nodeName === "PRE") {
            e.target.nextElementSibling.style.setProperty("--clipboard-image", "var(--clipboard-image-normal)")
        }
    })
    
    window.addEventListener("DOMContentLoaded", updatePreTags)

    

  
}
var Temporary1;
var t_553648167 = window.localStorage.getItem("theme");
if ((t_553648167 == null)) {
Temporary1 = "auto";
}
else {
Temporary1 = t_553648167;
}

setTheme(Temporary1);
var alternative_553648830 = [null];
var db_553648872 = [[]];
var contents_553648873 = [[]];
var oldtoc_553649207 = [null];
var timer_553649208 = [null];
var loadIndexFut_553649210 = [null];
copyToClipboard();
window.addEventListener("DOMContentLoaded", onDOMLoaded, false);
